name: Create Project from Template

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name of the new repository (kebab-case)'
        required: true
      team_name:
        description: 'Slug of the team that will own this repo (e.g. backend-team)'
        required: true
      description:
        description: 'Short project description'
        required: false

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create Repo from Template
        run: |
          gh repo create "KNMentorAGH/${{ github.event.inputs.repo_name }}" \
            --template "KNMentorAGH/template-project-name" \
            --public \
            --description "${{ github.event.inputs.description }}"
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}

      - name: Assign Team Permissions
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            /orgs/KNMentorAGH/teams/${{ github.event.inputs.team_name }}/repos/KNMentorAGH/${{ github.event.inputs.repo_name }} \
            -f permission='maintain'
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}