name: Create Project from Template

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name of the new repository (kebab-case)'
        required: true
      team_name:
        description: 'Slug of the team (e.g. projekt-yennefer)'
        required: true

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Team Membership
        run: |
          if ! gh api /orgs/KNMentorAGH/teams/${{ github.event.inputs.team_name }}/memberships/${{ github.actor }} --silent; then
            echo "::error::User ${{ github.actor }} is not a member of team ${{ github.event.inputs.team_name }} or team does not exist!"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}

      - name: Create Repo from Template
        run: |
          gh repo create "KNMentorAGH/${{ github.event.inputs.repo_name }}" \
            --template "KNMentorAGH/template" \
            --public
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}

      - name: Assign Team Permissions
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            /orgs/KNMentorAGH/teams/${{ github.event.inputs.team_name }}/repos/KNMentorAGH/${{ github.event.inputs.repo_name }} \
            -f permission='maintain'
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}