name: Create Project from Template

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name of the new repository (kebab-case)'
        required: true
      team_name:
        description: 'Slug of the team (e.g. projekt-yennefer)'
        required: true
      project_leader:
        description: 'GitHub Username of the Project Leader (Code Owner)'
        required: true

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Team Membership
        run: |
          if ! gh api /orgs/KNMentorAGH/teams/${{ github.event.inputs.team_name }}/memberships/${{ github.actor }} --silent; then
            echo "::error::User ${{ github.actor }} is not a member of team ${{ github.event.inputs.team_name }} or team does not exist!"
            exit 1
          fi

          if ! gh api /orgs/KNMentorAGH/teams/${{ github.event.inputs.team_name }}/memberships/${{ github.event.inputs.project_leader }} --silent; then
            echo "::error::Project leader (@${{ github.event.inputs.project_leader }}) is not a member of team ${{ github.event.inputs.team_name }}!"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}

      - name: Create Repo from Template
        run: |
          gh repo create "KNMentorAGH/${{ github.event.inputs.repo_name }}" \
            --template "KNMentorAGH/template" \
            --public
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}

      - name: Assign Team Permissions
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            /orgs/KNMentorAGH/teams/${{ github.event.inputs.team_name }}/repos/KNMentorAGH/${{ github.event.inputs.repo_name }} \
            -f permission='maintain'
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
      - name: Setup Code Owners
        run: |
          REPO_LOWER=$(echo "${{ github.event.inputs.repo_name }}" | tr '[:upper:]' '[:lower:]')
          
          CONTENT=$(echo "* @${{ github.event.inputs.project_leader }}" | base64)
          
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/KNMentorAGH/$REPO_LOWER/contents/.github/CODEOWNERS \
            -f message="chore: initialize CODEOWNERS [skip ci]" \
            -f content="$CONTENT"
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}